<?php

    require("../assets/show.php");
    
    $show_product=show();
  
?>

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin page</title>
    <script src="https://kit.fontawesome.com/0fc5bb7376.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../../css/normalise.css">
    <link rel="stylesheet" href="../../css/style.css">
    <link rel="shortcut icon" type="image/ico" href="../../images/favicon.ico"/>
</head>
<body>
    <header>
        <div class="headerAdmin">
            <a href="add.php">Ajouter un produit</a>
            <a href="index.php">Page d'administration</a>
            <a href="logout.php">Déconnexion</a>
        </div>
    </header>
    <main> 
            <?php
                if ($notification != ''):
            ?>
                <div class="notification">
                    <p> Erreur : </p>
                    <?= $notification; ?>
                </div>
            <?php
                endif;
            ?>
        <div class="shop">
            <?php foreach($show_product as $product): ?>

            <div class="product <?=$product->description ?>">
            <img src="uploads/<?=$product->picture ?>" alt="photo du produit">
            <div class="formulaire">
                <form method="post" class="admin" action="productUpdate.php">
                    <h3>Modfier les information du produit</h3>
                    <label>Nom :</label>
                    <input type="text"name="name" placeholder="Nom du produit" value="<?=$product->name ?>" required>

                    <label>Prix :</label>
                    <input type="number" name="price" placeholder="Prix" value="<?=$product->price ?>" required>

                    <label>Cathégorie :</label>
                    <input name="description" required placeholder="product1, product2, product3, product4, product5" value="<?=$product->description ?>" required>

                    <button type="submit" name="updateProduct" value="<?=$product->id ?>"> mettre à jour le produit</button>
                </form>
                
                <form method="post" class="admin" action="pictureUpdate.php" enctype="multipart/form-data">
                    <h3>Modifier l'image du produit</h3>
                    <label>Lien de l'image:</label>
                    <input type="file"name="picture" value="test">
                    <button type="submit" name="updatePicture" value="<?=$product->id ?>"> mettre à jour la photo</button>
                </form>

                <form method="post" class="admin" action="productDelete.php">
                    <h3>Supprimer un produit</h3>
                    <button type="submit" value="<?=$product->id ?>" name="id">Supprimer</button>
                </form>
            </div>
        </div>

    <?php endforeach?>
    </main>
</body>
</html>