<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin page</title>
    <script src="https://kit.fontawesome.com/0fc5bb7376.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../../css/normalise.css">
    <link rel="stylesheet" href="../../css/style.css">
    <link rel="shortcut icon" type="image/ico" href="../../images/favicon.ico"/>
</head>

<body>
    <header class="headerAdmin">
        <a href="logout.php">Déconnexion</a>
        <a href="logoutShop.php">Retourner au shop</a>
    </header>
    <main class="adminHome">
        <div>
            <a href="add.php">Ajouter un produit</a>
            <a href="delete.php">Supprimer/modifier un produit</a>
        </div>
    </main>
</body>