<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin page</title>
    <script src="https://kit.fontawesome.com/0fc5bb7376.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../../css/normalise.css">
    <link rel="stylesheet" href="../../css/style.css">
    <link rel="shortcut icon" type="image/ico" href="../../images/favicon.ico"/>
</head>

<body>

<main>
  <div class="login">  
    <form class="formulaire" action="loginTraitement.php" method="post">
    <h1>Page de connexion</h1> 
        <div>
          <input type="email" id="email" name="email" placeholder="name@example.com">
          <label for="email">Email</label>
        </div>
        <div>
          <input type="password" id="password" name="password" placeholder="Password">
          <label for="password">Mot de passe</label>
        </div>
        <button type="submit">Valider</button>
    </form>
  </div>
</main>    
</body>
</html>